
CREATE TABLE TBL_STOCK(
PRODUCT_ID VARCHAR2(6),
PRODUCT_NAME VARCHAR2(20),
QUANTITY_ON_HAND NUMBER(11),
PRODUCT_UNIT_PRICE NUMBER(11,2),
REORDER_LEVEL NUMBER(11),
CONSTRAINT PK00 PRIMARY KEY(PRODUCT_ID),
CONSTRAINT UQ01 UNIQUE(PRODUCT_NAME),
CONSTRAINT CH01 CHECK(QUANTITY_ON_HAND>=0),
CONSTRAINT CH02 CHECK(PRODUCT_UNIT_PRICE>=0),
CONSTRAINT CH03 CHECK(REORDER_LEVEL>=0));

CREATE TABLE TBL_SALES(
SALES_ID VARCHAR2(6),
SALES_DATE DATE,
PRODUCT_ID VARCHAR2(6),
QUANTITY_SOLD NUMBER(11),
SALES_PRICE_PER_UNIT NUMBER(11,2),
CONSTRAINT PK10 PRIMARY KEY(SALES_ID),
CONSTRAINT FK11 FOREIGN KEY(PRODUCT_ID) REFERENCES TBL_STOCK(PRODUCT_ID),
CONSTRAINT CH12 CHECK(QUANTITY_SOLD>=0),
CONSTRAINT CH13 CHECK(SALES_PRICE_PER_UNIT>=0));

INSERT INTO TBL_STOCK VALUES('RE1001','REDMI Note 3',20,12000,5);
INSERT INTO TBL_STOCK VALUES('ip1002','Iphone 5S',10,21000,2);
INSERT INTO TBL_STOCK VALUES('PA1003','Panasonic P55',50,5500,5);

CREATE SEQUENCE SEQ_SALES_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1004 INCREMENT BY 1;

CREATE VIEW V_SALES_REPORT AS SELECT SALES_ID,SALES_DATE,PRODUCT_ID,QUANTITY_SOLD,SALES_PRICE_PER_UNIT,
(SALES_PRICE_PER_UNIT-PRODUCT_UNIT_PRICE) PROFIT_AMOUNT FROM TBL_STOCK
NATURAL JOIN TBL_SALES ORDER BY PROFIT_AMOUNT DESC, SALES_ID ASC;
